### ISSUE TITLE
Warn about determinism

### ISSUE THREAD

**Issue by dantman** [JannicBeck/ngrx-undoable#3]
In order for the "action replay" style of undo history to work, the reducer must be deterministic.

i.e. Given the same set of actions, it must produce the same result.

I forgot about this when I switched from `redux-undo`. Normally redux works fine even if actions are a little non-deterministic.

In my case I generated UUIDs inside of my reducer for things that were being created. Which meant that when I ran an undo, it was possible that one action may generate data with a different id and a different action that used said id in its payload would break because the data with that id would be under a different id when actions were replayed.

I understand this was my fault and I'm working on fixing this (putting a UUID in my action's payload and generating ids deterministically based on it). But it would be good to add a warning to the library that unlike other parts of redux, this library needs reducers to be deterministic to work.

**Comment by JannicBeck** [comment]
We've all been there, I'll add a note that the wrapped reducer has to be pure in the readme.
