### ISSUE TITLE
Memoization

### ISSUE THREAD

**Issue by JannicBeck** [JannicBeck/ngrx-undoable#7]
Memoize past states inside a closure to optimise undo performance with very large number of actions.
[see](https://github.com/JannicBeck/undox/issues/3)

**Comment by julienmarantes** [comment]
Hello which would you advise to use between ngrx-undoable and undox ? 

Could you explain the difference ?

**Comment by JannicBeck** [comment]
Hey, there is not much of a difference between them, the API is slightly different but you can switch between them without much effort. At some point they might be merged to have the exact same API.

The reason for separate projects/packages was more of a naming thing since users of angular2/ngrx might not search for redux related projects, but rather ngrx-... and vice versa

That said there is also a different implementation approach:
With undox your state looks like this:
```
{
  history : [ { type: 'undox/INIT' }, { type: 'INCREMENT' } ],
  index   : 1
  present : 1
}
```
with ngrx-undoable
```
{
  past    : [ { type: 'ngrx-undoable/INIT' }, { type: 'INCREMENT' } ]
  present : 1
  future  : [ ]
}
```
so instead of future and past in undox there is just a history and an index which points at the latest action.

However this is an implementation detail and it doesn't matter if you are using the provided selectors by both packages.
ngrx-undoable might be more approachable without using selectors.
While undox is more elegant since undo/redo an action is just changing the index.
